### ISSUE TITLE
 Actividad 6 Proceso de Negocio en Bizagi con Web 30 Mejorado

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-con-web-30-mejorado-equipo-jad#1]
[Actividad 6 Proceso de Negocio en Bizagi con Web 30 Mejorado.pdf](https://github.com/user-attachments/files/17163752/Actividad.6.Proceso.de.Negocio.en.Bizagi.con.Web.30.Mejorado.pdf)

**Comment by MarcoRg06** [comment]
De acuerdo con la rúbrica obtuvieron el 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
